server:
  port: 8083

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ACCOUNTSERVICE
              uri: lb://ACCOUNTSERVICE
              predicates:
                - Path=/accounts/**
            - id: LOANSERVICE
              uri: lb://LOANSERVICE
              predicates:
                - Path=/loans/**




eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


